# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created: Wed Nov 27 22:41:09 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 572)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-160, 120, 731, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("車子.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-70, -40, 871, 541))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("箭頭.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 731, 551))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("車子.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.text_A = QtWidgets.QLabel(Form)
        self.text_A.setGeometry(QtCore.QRect(20, 330, 67, 41))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.text_A.setFont(font)
        self.text_A.setAlignment(QtCore.Qt.AlignCenter)
        self.text_A.setObjectName("text_A")
        self.text_B = QtWidgets.QLabel(Form)
        self.text_B.setGeometry(QtCore.QRect(450, 330, 67, 41))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.text_B.setFont(font)
        self.text_B.setAlignment(QtCore.Qt.AlignCenter)
        self.text_B.setObjectName("text_B")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(-240, -30, 871, 521))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("箭頭2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(-10, 170, 131, 141))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("A區.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(440, 170, 131, 141))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("B區.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.text_count = QtWidgets.QLabel(Form)
        self.text_count.setGeometry(QtCore.QRect(250, 120, 67, 51))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.text_count.setFont(font)
        self.text_count.setAlignment(QtCore.Qt.AlignCenter)
        self.text_count.setObjectName("text_count")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(140, 10, 281, 91))
        font = QtGui.QFont()
        font.setFamily("Accanthis ADF Std")
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 440, 261, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(-1, -1, 1, -1)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.eleven = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eleven.setFont(font)
        self.eleven.setAlignment(QtCore.Qt.AlignCenter)
        self.eleven.setObjectName("eleven")
        self.gridLayout.addWidget(self.eleven, 0, 5, 1, 1)
        self.seven = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.seven.setFont(font)
        self.seven.setAlignment(QtCore.Qt.AlignCenter)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 0, 1, 1, 1)
        self.twelve = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.twelve.setFont(font)
        self.twelve.setAlignment(QtCore.Qt.AlignCenter)
        self.twelve.setObjectName("twelve")
        self.gridLayout.addWidget(self.twelve, 0, 6, 1, 1)
        self.six = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.six.setFont(font)
        self.six.setAlignment(QtCore.Qt.AlignCenter)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 0, 0, 1, 1)
        self.nine = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nine.setFont(font)
        self.nine.setAlignment(QtCore.Qt.AlignCenter)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 0, 3, 1, 1)
        self.fifteen = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fifteen.setFont(font)
        self.fifteen.setAlignment(QtCore.Qt.AlignCenter)
        self.fifteen.setObjectName("fifteen")
        self.gridLayout.addWidget(self.fifteen, 0, 9, 1, 1)
        self.thirteen = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.thirteen.setFont(font)
        self.thirteen.setAlignment(QtCore.Qt.AlignCenter)
        self.thirteen.setObjectName("thirteen")
        self.gridLayout.addWidget(self.thirteen, 0, 7, 1, 1)
        self.ten = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ten.setFont(font)
        self.ten.setAlignment(QtCore.Qt.AlignCenter)
        self.ten.setObjectName("ten")
        self.gridLayout.addWidget(self.ten, 0, 4, 1, 1)
        self.eight = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.eight.setFont(font)
        self.eight.setAlignment(QtCore.Qt.AlignCenter)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 0, 2, 1, 1)
        self.fourteen = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fourteen.setFont(font)
        self.fourteen.setAlignment(QtCore.Qt.AlignCenter)
        self.fourteen.setObjectName("fourteen")
        self.gridLayout.addWidget(self.fourteen, 0, 8, 1, 1)
        self.sixteen = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sixteen.setFont(font)
        self.sixteen.setAlignment(QtCore.Qt.AlignCenter)
        self.sixteen.setObjectName("sixteen")
        self.gridLayout.addWidget(self.sixteen, 0, 10, 1, 1)
        self.zero = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.zero.setFont(font)
        self.zero.setAlignment(QtCore.Qt.AlignCenter)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 1, 2, 1, 1)
        self.one = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.one.setFont(font)
        self.one.setAlignment(QtCore.Qt.AlignCenter)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 1, 3, 1, 1)
        self.two = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.two.setFont(font)
        self.two.setAlignment(QtCore.Qt.AlignCenter)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 1, 4, 1, 1)
        self.three = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.three.setFont(font)
        self.three.setAlignment(QtCore.Qt.AlignCenter)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 1, 5, 1, 1)
        self.four = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.four.setFont(font)
        self.four.setAlignment(QtCore.Qt.AlignCenter)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 6, 1, 1)
        self.five = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.five.setFont(font)
        self.five.setAlignment(QtCore.Qt.AlignCenter)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 7, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(290, 450, 261, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 1, -1)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.num7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num7.setFont(font)
        self.num7.setAlignment(QtCore.Qt.AlignCenter)
        self.num7.setObjectName("num7")
        self.gridLayout_3.addWidget(self.num7, 0, 1, 1, 1)
        self.num15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num15.setFont(font)
        self.num15.setAlignment(QtCore.Qt.AlignCenter)
        self.num15.setObjectName("num15")
        self.gridLayout_3.addWidget(self.num15, 0, 9, 1, 1)
        self.num14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num14.setFont(font)
        self.num14.setAlignment(QtCore.Qt.AlignCenter)
        self.num14.setObjectName("num14")
        self.gridLayout_3.addWidget(self.num14, 0, 8, 1, 1)
        self.num13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num13.setFont(font)
        self.num13.setAlignment(QtCore.Qt.AlignCenter)
        self.num13.setObjectName("num13")
        self.gridLayout_3.addWidget(self.num13, 0, 7, 1, 1)
        self.num4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num4.setFont(font)
        self.num4.setAlignment(QtCore.Qt.AlignCenter)
        self.num4.setObjectName("num4")
        self.gridLayout_3.addWidget(self.num4, 1, 6, 1, 1)
        self.num0 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num0.setFont(font)
        self.num0.setAlignment(QtCore.Qt.AlignCenter)
        self.num0.setObjectName("num0")
        self.gridLayout_3.addWidget(self.num0, 1, 2, 1, 1)
        self.num10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num10.setFont(font)
        self.num10.setAlignment(QtCore.Qt.AlignCenter)
        self.num10.setObjectName("num10")
        self.gridLayout_3.addWidget(self.num10, 0, 4, 1, 1)
        self.num8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num8.setFont(font)
        self.num8.setAlignment(QtCore.Qt.AlignCenter)
        self.num8.setObjectName("num8")
        self.gridLayout_3.addWidget(self.num8, 0, 2, 1, 1)
        self.num5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num5.setFont(font)
        self.num5.setAlignment(QtCore.Qt.AlignCenter)
        self.num5.setObjectName("num5")
        self.gridLayout_3.addWidget(self.num5, 1, 7, 1, 1)
        self.num1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num1.setFont(font)
        self.num1.setAlignment(QtCore.Qt.AlignCenter)
        self.num1.setObjectName("num1")
        self.gridLayout_3.addWidget(self.num1, 1, 3, 1, 1)
        self.num3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num3.setFont(font)
        self.num3.setAlignment(QtCore.Qt.AlignCenter)
        self.num3.setObjectName("num3")
        self.gridLayout_3.addWidget(self.num3, 1, 5, 1, 1)
        self.num2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num2.setFont(font)
        self.num2.setAlignment(QtCore.Qt.AlignCenter)
        self.num2.setObjectName("num2")
        self.gridLayout_3.addWidget(self.num2, 1, 4, 1, 1)
        self.num9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num9.setFont(font)
        self.num9.setAlignment(QtCore.Qt.AlignCenter)
        self.num9.setObjectName("num9")
        self.gridLayout_3.addWidget(self.num9, 0, 3, 1, 1)
        self.num12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num12.setFont(font)
        self.num12.setAlignment(QtCore.Qt.AlignCenter)
        self.num12.setObjectName("num12")
        self.gridLayout_3.addWidget(self.num12, 0, 6, 1, 1)
        self.num6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num6.setFont(font)
        self.num6.setAlignment(QtCore.Qt.AlignCenter)
        self.num6.setObjectName("num6")
        self.gridLayout_3.addWidget(self.num6, 0, 0, 1, 1)
        self.num11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num11.setFont(font)
        self.num11.setAlignment(QtCore.Qt.AlignCenter)
        self.num11.setObjectName("num11")
        self.gridLayout_3.addWidget(self.num11, 0, 5, 1, 1)
        self.num16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.num16.setFont(font)
        self.num16.setAlignment(QtCore.Qt.AlignCenter)
        self.num16.setObjectName("num16")
        self.gridLayout_3.addWidget(self.num16, 0, 10, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(330, 400, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "停車位資訊"))
        self.text_A.setText(_translate("Form", "TextLabel"))
        self.text_B.setText(_translate("Form", "TextLabel"))
        self.text_count.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "剩餘停車位總數"))
        self.eleven.setText(_translate("Form", "TextLabel"))
        self.seven.setText(_translate("Form", "TextLabel"))
        self.twelve.setText(_translate("Form", "TextLabel"))
        self.six.setText(_translate("Form", "TextLabel"))
        self.nine.setText(_translate("Form", "TextLabel"))
        self.fifteen.setText(_translate("Form", "TextLabel"))
        self.thirteen.setText(_translate("Form", "TextLabel"))
        self.ten.setText(_translate("Form", "TextLabel"))
        self.eight.setText(_translate("Form", "TextLabel"))
        self.fourteen.setText(_translate("Form", "TextLabel"))
        self.sixteen.setText(_translate("Form", "TextLabel"))
        self.zero.setText(_translate("Form", "TextLabel"))
        self.one.setText(_translate("Form", "TextLabel"))
        self.two.setText(_translate("Form", "TextLabel"))
        self.three.setText(_translate("Form", "TextLabel"))
        self.four.setText(_translate("Form", "TextLabel"))
        self.five.setText(_translate("Form", "TextLabel"))
        self.num7.setText(_translate("Form", "TextLabel"))
        self.num15.setText(_translate("Form", "TextLabel"))
        self.num14.setText(_translate("Form", "TextLabel"))
        self.num13.setText(_translate("Form", "TextLabel"))
        self.num4.setText(_translate("Form", "TextLabel"))
        self.num0.setText(_translate("Form", "TextLabel"))
        self.num10.setText(_translate("Form", "TextLabel"))
        self.num8.setText(_translate("Form", "TextLabel"))
        self.num5.setText(_translate("Form", "TextLabel"))
        self.num1.setText(_translate("Form", "TextLabel"))
        self.num3.setText(_translate("Form", "TextLabel"))
        self.num2.setText(_translate("Form", "TextLabel"))
        self.num9.setText(_translate("Form", "TextLabel"))
        self.num12.setText(_translate("Form", "TextLabel"))
        self.num6.setText(_translate("Form", "TextLabel"))
        self.num11.setText(_translate("Form", "TextLabel"))
        self.num16.setText(_translate("Form", "TextLabel"))
        self.label_5.setText(_translate("Form", "空車位"))
        self.label_9.setText(_translate("Form", "空車位"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

