# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created: Thu Oct 24 10:21:01 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1209, 766)
        Form.setMinimumSize(QtCore.QSize(250, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Text_time = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Text_time.setFont(font)
        self.Text_time.setText("")
        self.Text_time.setObjectName("Text_time")
        self.verticalLayout.addWidget(self.Text_time)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.remain_tab = QtWidgets.QWidget()
        self.remain_tab.setObjectName("remain_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.remain_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.remain_tab)
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(500, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 586))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Entrance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Entrance.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.Entrance.setFont(font)
        self.Entrance.setObjectName("Entrance")
        self.verticalLayout_6.addWidget(self.Entrance)
        self.areaB = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.areaB.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.areaB.setFont(font)
        self.areaB.setObjectName("areaB")
        self.verticalLayout_6.addWidget(self.areaB)
        self.areaA = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.areaA.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.areaA.setFont(font)
        self.areaA.setObjectName("areaA")
        self.verticalLayout_6.addWidget(self.areaA)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textCount = QtWidgets.QLabel(self.remain_tab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.textCount.setFont(font)
        self.textCount.setAutoFillBackground(False)
        self.textCount.setScaledContents(False)
        self.textCount.setObjectName("textCount")
        self.verticalLayout_2.addWidget(self.textCount)
        self.textAremain = QtWidgets.QLabel(self.remain_tab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.textAremain.setFont(font)
        self.textAremain.setObjectName("textAremain")
        self.verticalLayout_2.addWidget(self.textAremain)
        self.textBremain = QtWidgets.QLabel(self.remain_tab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.textBremain.setFont(font)
        self.textBremain.setObjectName("textBremain")
        self.verticalLayout_2.addWidget(self.textBremain)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.remain_tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 506, 586))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.text_detail = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_detail.setFont(font)
        self.text_detail.setText("")
        self.text_detail.setObjectName("text_detail")
        self.verticalLayout_7.addWidget(self.text_detail)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.remain_tab, "")
        self.space_tab = QtWidgets.QWidget()
        self.space_tab.setObjectName("space_tab")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.space_tab)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 10, 991, 581))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 989, 579))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectYMLtitle = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.selectYMLtitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectYMLtitle.setObjectName("selectYMLtitle")
        self.verticalLayout_3.addWidget(self.selectYMLtitle)
        self.parkspace = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.parkspace.setText("")
        self.parkspace.setObjectName("parkspace")
        self.verticalLayout_3.addWidget(self.parkspace)
        self.selectYML_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.selectYML_btn.setObjectName("selectYML_btn")
        self.verticalLayout_3.addWidget(self.selectYML_btn)
        self.displayYMLpath = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.displayYMLpath.setObjectName("displayYMLpath")
        self.verticalLayout_3.addWidget(self.displayYMLpath)
        self.confirm_path_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.confirm_path_btn.setObjectName("confirm_path_btn")
        self.verticalLayout_3.addWidget(self.confirm_path_btn)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.tabWidget.addTab(self.space_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.control_bt.setObjectName("control_bt")
        self.verticalLayout.addWidget(self.control_bt)
        self.close_bt = QtWidgets.QPushButton(Form)
        self.close_bt.setObjectName("close_bt")
        self.verticalLayout.addWidget(self.close_bt)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "影像辨識智慧停車場系統"))
        self.Entrance.setText(_translate("Form", "入口影像"))
        self.areaB.setText(_translate("Form", "A區影像"))
        self.areaA.setText(_translate("Form", "B區影像"))
        self.textCount.setText(_translate("Form", "入口 ： "))
        self.textAremain.setText(_translate("Form", "A區 ： "))
        self.textBremain.setText(_translate("Form", "B區 ： "))
        self.label.setText(_translate("Form", "詳細資料"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.remain_tab), _translate("Form", "剩餘車輛數"))
        self.selectYMLtitle.setText(_translate("Form", "選擇一個YML檔案..."))
        self.selectYML_btn.setText(_translate("Form", "選擇"))
        self.displayYMLpath.setText(_translate("Form", "檔案路徑"))
        self.confirm_path_btn.setText(_translate("Form", "確認"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.space_tab), _translate("Form", "停車格辨識"))
        self.control_bt.setText(_translate("Form", "開始"))
        self.close_bt.setText(_translate("Form", "關閉"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

